before_script:
- ls -la

variables:
  DATABASE_SECRET: "aGVsbG8K"
  DATABASE_HOST: "127.0.0.1"
  SERVER_HOST: "127.0.0.1:5000"

server-unit-test:
  stage: test
  script:
  - sh run gen-secrets prod
  - cd server
  - sh run docker-test

client-unit-test:
  stage: test
  script:
  - sh run gen-secrets prod
  - cd client
  - yarn run docker-test