before_script:
- ls -la
- pwd

variables:
  DATABASE_SECRET: "aGVsbG8K"
  DATABASE_HOST: "127.0.0.1"
  SERVER_HOST: "127.0.0.1:5000"

server-unit-tests:
  stage: test
  script:
  - sh run gen-secrets prod
  - cd server
  - sh run docker-test

client-unit-tests:
  stage: test
  script:
  - sh run gen-secrets prod
  - cd client
  - sh run docker-test

server-postman-tests:
  stage: test
  script:
  - sh run gen-secrets prod
  - docker create --name ${CI_COMMIT_SHA} --env-file ./secrets.env mariadb"
  - cd server
  - sh run postman-test
  - docker stop ${CI_COMMIT_SHA}
  - docker rm ${CI_COMMIT_SHA}