before_script:
- ls -la
- pwd

variables:
  DATABASE_SECRET: "aGVsbG8K"
  DATABASE_HOST: "127.0.0.1"
  SERVER_HOST: "127.0.0.1:5000"

server-tests:
  stage: test
  script:
  - sh run gen-secrets prod
  - cd server
  - sh run docker-test

client-tests:
  stage: test
  script:
  - sh run gen-secrets prod
  - cd client
  - sh run docker-test