#!/bin/bash

if [ -z $1 ]
then
  env='dev'
else
  env=$1
fi

if [ -z $APPLICATION_SECRET ]
then
  echo APPLICATION_SECRET not found.
  echo
  echo We will now generate your secret
  read -p 'Please enter your database password: ' db_pass
  echo
  echo Generating secret...
  encoded_secret=$( echo $db_pass | base64 )
  echo
  echo You APPLICATION_SECRET is:
  echo $encoded_secret
  echo
else
  echo APPLICATION_SECRET found.
  echo
  db_pass=$( echo $APPLICATION_SECRET | base64 -d )
fi

echo Using secret...
echo

if [ -z $DATABASE_HOST ]
then
  echo DATABASE_HOST not found.
  echo
  if [ $env = 'prod' ]
  then
    db_host="mariadb"
  else
    db_host="192.168.88.88"
  fi
  echo "Using default host ($db_host)"
  echo
else
  echo DATABASE_HOST found.
  echo
  echo Using host...
  echo
  db_host=$DATABASE_HOST
fi

if [ -z $CLIENT_HOST ]
then
  echo CLIENT_HOST not found.
  echo
  if [ $env = 'prod' ]
  then
    client_host="192.168.88.88"
  else
    client_host="127.0.0.1:5000"
  fi
  echo "Using default host ($client_host)"
  echo
else
  echo CLIENT_HOST found.
  echo
  echo Using host...
  echo
  client_host=$CLIENT_HOST
fi

echo Generating secrets file for database...
cp mariadb/secrets.env.sample mariadb/secrets.env
sed -i "s/<password>/$db_pass/g" mariadb/secrets.env

echo Generating secrets file for server...
cp server/server/secrets.json.sample server/server/secrets.json
sed -i "s/<password>/$db_pass/g" server/server/secrets.json
sed -i "s/<host>/$db_host/g" server/server/secrets.json

echo Generating secrets file for client...
cp client/secrets.json.sample client/secrets.json
sed -i "s/<host>/$client_host/g" client/secrets.json

echo Secret files generated!